//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TableCusOrders1081728
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableCusOrders1081728()
        {
            this.TableCusOrderDetails1081728 = new HashSet<TableCusOrderDetails1081728>();
        }

        public int Id { get; set; }

        [DisplayName("訂單編號")]
        public string OrderGuid { get; set; }

        [DisplayName("會員帳號")]
        public string UserId { get; set; }

        [DisplayName("收件人姓名")]
        [Required(ErrorMessage = "收件人姓名不可空白")]
        public string Receiver { get; set; }

        [DisplayName("收件人信箱")]
        [EmailAddress(ErrorMessage = "E-Mail 格式有誤")]
        [Required]
        public string ReEmail { get; set; }

        [DisplayName("收件人地址")]
        [Required(ErrorMessage = "收件人地址不可空白")]
        public string ReOrderAddress { get; set; }

        [DisplayName("訂單日期")]
        [DataType(DataType.Date)]
        public System.DateTime ReDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableCusOrderDetails1081728> TableCusOrderDetails1081728 { get; set; }
    }
}
